version: '3'

tasks:
  build:
    cmds:
      - | 
        docker build -t duo_php -f- . <<EOF
            FROM php:8
                  EXPOSE 8080
                  RUN apt update && apt install -y unzip wget
                  WORKDIR /root
                  RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/885ece8a6e1370b204b89b7a542169d25aa21177/web/installer -O - -q | php -- --quiet

                  WORKDIR /src
                  ADD ./composer.json /src/composer.json
                  RUN /root/composer.phar update
                  ADD . /src
        EOF

  test:
    deps: [build]
    cmds:
      - docker run --rm -it duo_php /src/vendor/bin/phpunit --process-isolation tests
  shell:
    deps: [build]
    cmds:
      - docker run --rm -it duo_php bash

#1. Build the docker image: `docker build -t duo_php_example .`
#1. Run the docker container `docker run -p 8080:8080 duo_php_example`
